import {chromium,CHROME_PATH} from './helpers/browser-runtime.mjs';import {mkdirSync,writeFileSync,readFileSync} from 'node:fs';import assert from 'node:assert/strict';
const BASE=process.env.PORTAL_TEST_URL??'http://127.0.0.1:8080',OUT=process.env.PORTAL_TEST_OUT??'docs/photoreal-evidence',backends=(process.env.PORTAL_BACKENDS??'webgpu,webgl2').split(','),tiers=(process.env.PORTAL_TIERS??'low,medium,high,cinematic').split(',');
mkdirSync(OUT,{recursive:true});const manifest=JSON.parse(readFileSync('assets/shaders/manifest.json','utf8')),report={date:new Date().toISOString(),source:manifest.sourceSha256,browser:CHROME_PATH,viewport:[1280,720],prepareTimeoutOverride:process.env.PORTAL_PREPARE_TIMEOUT?Number(process.env.PORTAL_PREPARE_TIMEOUT):null,method:'WebGPU timestamps when available; GL gl.finish plus 1px readback. Per scene: 15 warmup, 60 measured frames.',results:[],errors:[]};
const browser=await chromium.launch({executablePath:CHROME_PATH,headless:true,args:['--use-angle=d3d11']});
try{for(const backend of backends){const page=await browser.newPage({viewport:{width:1280,height:720}});page.setDefaultTimeout(240000);page.on('pageerror',e=>report.errors.push(e.message));page.on('console',m=>{if(m.type()==='error')report.errors.push(m.text());});await page.goto(BASE+'/tests/photoreal-host.html');
 await page.evaluate(async backend=>{const {GameEngine}=await import('/src/physics.js'),{CAMPAIGN_LEVELS}=await import('/src/campaign.js'),{DEFAULT_SETTINGS}=await import('/src/storage.js');const c=document.querySelector('canvas');let r;const options={quality:'low',deferProgram:true,onContextLost:e=>console.error(e?.message??'context lost')};if(backend==='webgpu'){const {WebGPURenderer}=await import('/src/renderer-webgpu.js');r=await WebGPURenderer.create(c,options);}else{if(backend==='webgl1')c.getContext=new Proxy(c.getContext,{apply:(fn,target,args)=>args[0]==='webgl2'?null:Reflect.apply(fn,target,args)});const {Renderer}=await import('/src/renderer.js');r=new Renderer(c,options);r.externallyTimed=true;r.asyncCompile=true;}window.probe={r,engine:new GameEngine(CAMPAIGN_LEVELS),settings:{...DEFAULT_SETTINGS,dynamicCamera:true,effects:true}};window.probe.draw=async()=>{const {r,engine,settings}=window.probe,t=performance.now();await r.draw(engine,settings);if(r.gl){r.gl.finish();const px=new Uint8Array(4);r.gl.readPixels(r.canvas.width>>1,r.canvas.height>>1,1,1,r.gl.RGBA,r.gl.UNSIGNED_BYTE,px);if(r.gl.getError()!==r.gl.NO_ERROR)throw Error('GL draw failed');}return {wall:performance.now()-t,gpu:r.lastGPUCost??null};};},backend);
 if(process.env.PORTAL_PREPARE_TIMEOUT)await page.evaluate(ms=>window.probe.prepareTimeoutMs=Number(ms),process.env.PORTAL_PREPARE_TIMEOUT);
 for(const tier of tiers){console.log('Preparing',backend,tier);const result=await page.evaluate(async tier=>{const {r,engine,draw}=window.probe,t=performance.now();await r.requestQuality(tier,window.probe.prepareTimeoutMs?{prepareTimeoutMs:window.probe.prepareTimeoutMs}:{});const prepare=performance.now()-t,scenes=[];for(const level of [0,6,14,21]){engine.reset(level);if(level===21)engine.state.seq=3;for(let i=0;i<15;i++)await draw();const measured=[];for(let i=0;i<60;i++)measured.push(await draw());const stats=key=>{const data=measured.map(x=>x[key]).filter(x=>x!==null).sort((a,b)=>a-b);return data.length?{samples:data.length,mean:data.reduce((a,b)=>a+b,0)/data.length,p95:data[Math.ceil(data.length*.95)-1],p99:data[Math.ceil(data.length*.99)-1],worst:data.at(-1)}:null;};scenes.push({level:level+1,wall:stats('wall'),gpu:stats('gpu')});}return {tier,prepare,size:[r.canvas.width,r.canvas.height],description:r.description(),allocatedTargetBytes:r.allocatedTargetBytes??r.canvas.width*r.canvas.height*(r.post?24:0)+(r.surfaceTarget?r.surfaceTarget.width*r.surfaceTarget.height*4:0),scenes};},tier);report.results.push({backend,...result});writeFileSync(OUT+'/render-final.json',JSON.stringify(report,null,2)+'\n');await page.screenshot({path:OUT+'/'+backend+'-'+tier+'-portal.png'});console.log('Measured',backend,tier,'prepare',result.prepare,'ms','GPU/Wall p95',result.scenes.map(s=>s.gpu?.p95??s.wall.p95));}
 if(backend!=='webgl1'){const photo=await page.evaluate(async()=>{const {r,engine,draw}=window.probe;engine.reset(0);const state=JSON.stringify(engine.state);r.startPhoto();while(r.photo.active)await draw();assertState();function assertState(){if(JSON.stringify(engine.state)!==state)throw Error('Photo changed domain state');}return r.photo.count;});assert.equal(photo,32);await page.screenshot({path:OUT+'/'+backend+'-photo.png'});await page.setViewportSize({width:360,height:640});await page.evaluate(async()=>{window.probe.r.resize();await window.probe.draw();});await page.screenshot({path:OUT+'/'+backend+'-portrait.png'});}
 await page.evaluate(()=>window.probe.r.destroy());await page.close();}
 assert.deepEqual(report.errors,[]);console.log('PASS renderer profiles, scenes, photo, resize and cleanup');
}catch(error){report.errors.push(error.stack);throw error;}finally{writeFileSync(OUT+'/render-final.json',JSON.stringify(report,null,2)+'\n');await browser.close();}
