import test from 'node:test';import assert from 'node:assert/strict';import {PhotoSequence,PHOTO_SAMPLES} from '../src/photo-sequence.js';import {vulkanShader} from '../scripts/shader-source.mjs';
test('photo completes exactly 32 valid samples and reaches rest',()=>{const p=new PhotoSequence();p.start();for(let i=0;i<32;i++){const s=p.next();assert.equal(s.weight,1/(i+1));assert(s.jitter.every(x=>x>=-.5&&x<.5));assert(p.commit(s));}assert.equal(p.count,PHOTO_SAMPLES);assert.equal(p.next(),null);});
test('cancel and replacement reject stale photo commits',()=>{const p=new PhotoSequence();p.start();const a=p.next();p.reset();assert.equal(p.commit(a),false);p.start();assert.equal(p.commit(a),false);assert.equal(p.count,0);});
test('twenty cycles have no retained samples and deterministic jitter',()=>{const p=new PhotoSequence();for(let i=0;i<20;i++){p.start();const s=p.next();assert.equal(s.jitter[0],0);assert(Math.abs(s.jitter[1]+1/6)<1e-15);p.commit(s);p.reset();assert.equal(p.next(),null);assert.equal(p.count,0);}});
test('all WGSL variants share ABI and correct coordinate origins',()=>{let abi;for(const tier of ['low','medium','high','cinematic'])for(const pass of ['surface','shade','combined']){const v=vulkanShader(tier,pass);abi??=v.uniforms;assert.deepEqual(v.uniforms,abi);assert.match(v.source,/uniforms.uRes.y-gl_FragCoord.y/);assert.doesNotMatch(v.source,/uniform sampler2D/);if(pass==='shade')assert.match(v.source,/textureLod\(uSurfaceHits,gl_FragCoord.xy\/uniforms.uRes.xy,0.\)/);}});

import {fragmentShader} from '../src/shaders.js';
test('timber joints and relief share authored metric dimensions',()=>{const shader=fragmentShader('high');assert.match(shader,/#define WOOD_BOARD_WIDTH .22/);assert.match(shader,/#define WOOD_BOARD_LENGTH 1.65/);assert.match(shader,/stripeCoverage\(q.x\+3.25,WOOD_BOARD_WIDTH/);assert.match(shader,/filteredStripe\(uv.x\+3.25,WOOD_BOARD_WIDTH/);});
test('interior illumination integrates visible strips without stochastic lighting',()=>{const shader=fragmentShader('high');const body=shader.slice(shader.indexOf('vec3 stripLighting('),shader.indexOf('vec3 environment('));assert.match(body,/for\(int i=0;i<2;i\+\+\)/);assert.doesNotMatch(body,/uTime|hash\(|noise\(/);assert.match(shader,/vec3 lp=vec3\(0,3.045,-1.65\)/);});

import {glsl300} from '../src/gl-formats.js';
test('GLSL300 conversion handles reserved local identifiers and core derivatives',()=>{const source=glsl300(fragmentShader('high','highp',{derivatives:true,hdr:true}));assert.match(source,/^#version 300 es/);assert.doesNotMatch(source,/\bvec2 sample=/);assert.doesNotMatch(source,/#extension GL_OES_standard_derivatives/);assert.match(source,/out vec4 fragColor/);});

import {createHash} from 'node:crypto';import {readFileSync} from 'node:fs';
test('published WGSL assets match the exact reviewed source and manifest',()=>{const manifest=JSON.parse(readFileSync(new URL('../assets/shaders/manifest.json',import.meta.url)));const digest=bytes=>createHash('sha256').update(bytes).digest('hex');assert.equal(manifest.sourceSha256,digest(readFileSync(new URL('../src/shaders.js',import.meta.url))));for(const [name,meta] of Object.entries(manifest.variants)){const bytes=readFileSync(new URL('../assets/shaders/'+name+'.wgsl',import.meta.url));assert.equal(bytes.length,meta.bytes);assert.equal(digest(bytes),meta.sha256);}});
