import {PhotoSequence} from './photo-sequence.js';
const VERTEX=`#version 300 es
in vec2 aPos;out vec2 uv;void main(){uv=aPos*.5+.5;gl_Position=vec4(aPos,0,1);}`;
const FRAGMENT=`#version 300 es
precision highp float;
in vec2 uv;out vec4 fragColor;uniform sampler2D current,history;uniform vec2 pixel;uniform float weight,mode;
float lum(vec3 c){return dot(c,vec3(.2126,.7152,.0722));}
vec3 radiance(vec2 p){return texture(current,p).rgb;}
vec3 aa(vec2 p){vec3 c=radiance(p),nw=radiance(p+pixel*vec2(-1,-1)),ne=radiance(p+pixel*vec2(1,-1)),sw=radiance(p+pixel*vec2(-1,1)),se=radiance(p+pixel*vec2(1,1));vec4 l=vec4(lum(nw),lum(ne),lum(sw),lum(se));float lc=lum(c),lo=min(lc,min(min(l.x,l.y),min(l.z,l.w))),hi=max(lc,max(max(l.x,l.y),max(l.z,l.w)));if(hi-lo<max(.025,hi*.10))return c;vec2 direction=vec2(-(l.x+l.y-l.z-l.w),l.x+l.z-l.y-l.w);float reduction=max(dot(l,vec4(.03125)),.0078125);direction=clamp(direction/(min(abs(direction.x),abs(direction.y))+reduction),vec2(-4),vec2(4))*pixel;vec3 a=(radiance(p+direction*(-1./6.))+radiance(p+direction*(1./6.)))*.5,b=a*.5+(radiance(p+direction*(-.5))+radiance(p+direction*.5))*.25;float lb=lum(b);return lb<lo||lb>hi?a:b;}
vec3 aces(vec3 c){return clamp((c*(2.51*c+.03))/(c*(2.43*c+.59)+.14),0.,1.);}
void main(){vec3 c=radiance(uv);if(mode<.5)c=aa(uv);if(mode>1.5){if(weight<1.)c=mix(texture(history,uv).rgb,c,weight);fragColor=vec4(c,1);return;}fragColor=vec4(pow(aces(max(c,vec3(0))),vec3(1./2.2)),1);}`;
export class GLPost{
 constructor(gl,quad){this.gl=gl;this.quad=quad;this.photo=new PhotoSequence();const compile=(type,source)=>{const shader=gl.createShader(type);gl.shaderSource(shader,source);gl.compileShader(shader);if(!gl.getShaderParameter(shader,gl.COMPILE_STATUS)){const text=gl.getShaderInfoLog(shader);gl.deleteShader(shader);throw Error(text);}return shader;};let vs,fs;try{vs=compile(gl.VERTEX_SHADER,VERTEX);fs=compile(gl.FRAGMENT_SHADER,FRAGMENT);this.program=gl.createProgram();gl.attachShader(this.program,vs);gl.attachShader(this.program,fs);gl.linkProgram(this.program);if(!gl.getProgramParameter(this.program,gl.LINK_STATUS))throw Error(gl.getProgramInfoLog(this.program));this.position=gl.getAttribLocation(this.program,'aPos');this.uniforms=Object.fromEntries(['current','history','pixel','weight','mode'].map(n=>[n,gl.getUniformLocation(this.program,n)]));}catch(error){if(this.program)gl.deleteProgram(this.program);throw error;}finally{if(vs)gl.deleteShader(vs);if(fs)gl.deleteShader(fs);}}
 target(width,height){const gl=this.gl,texture=gl.createTexture(),framebuffer=gl.createFramebuffer();try{gl.bindTexture(gl.TEXTURE_2D,texture);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MIN_FILTER,gl.LINEAR);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MAG_FILTER,gl.LINEAR);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_WRAP_S,gl.CLAMP_TO_EDGE);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_WRAP_T,gl.CLAMP_TO_EDGE);gl.texImage2D(gl.TEXTURE_2D,0,gl.RGBA16F,width,height,0,gl.RGBA,gl.HALF_FLOAT,null);gl.bindFramebuffer(gl.FRAMEBUFFER,framebuffer);gl.framebufferTexture2D(gl.FRAMEBUFFER,gl.COLOR_ATTACHMENT0,gl.TEXTURE_2D,texture,0);if(gl.checkFramebufferStatus(gl.FRAMEBUFFER)!==gl.FRAMEBUFFER_COMPLETE)throw Error('No hay framebuffer HDR válido.');return {texture,framebuffer};}catch(error){gl.deleteTexture(texture);gl.deleteFramebuffer(framebuffer);throw error;}}
 resize(width,height){if(this.width===width&&this.height===height)return;this.release();this.width=width;this.height=height;try{this.current=this.target(width,height);this.history=[];for(let i=0;i<2;i++)this.history.push(this.target(width,height));this.index=0;this.photo.reset();}catch(error){this.release();throw error;}finally{this.gl.bindFramebuffer(this.gl.FRAMEBUFFER,null);}}
 resolve(sample){const gl=this.gl,u=this.uniforms;gl.useProgram(this.program);gl.bindBuffer(gl.ARRAY_BUFFER,this.quad);gl.enableVertexAttribArray(this.position);gl.vertexAttribPointer(this.position,2,gl.FLOAT,false,0,0);gl.viewport(0,0,this.width,this.height);gl.uniform2f(u.pixel,1/this.width,1/this.height);gl.uniform1i(u.current,2);gl.uniform1i(u.history,3);gl.activeTexture(gl.TEXTURE2);gl.bindTexture(gl.TEXTURE_2D,this.current.texture);gl.activeTexture(gl.TEXTURE3);gl.bindTexture(gl.TEXTURE_2D,this.history[this.index].texture);
  if(sample){const next=this.history[1-this.index];gl.bindFramebuffer(gl.FRAMEBUFFER,next.framebuffer);gl.uniform1f(u.weight,sample.weight);gl.uniform1f(u.mode,2);gl.drawArrays(gl.TRIANGLES,0,3);gl.activeTexture(gl.TEXTURE2);gl.bindTexture(gl.TEXTURE_2D,next.texture);this.index=1-this.index;this.photo.commit(sample);}
  gl.bindFramebuffer(gl.FRAMEBUFFER,null);gl.uniform1f(u.mode,sample?1:0);gl.drawArrays(gl.TRIANGLES,0,3);gl.activeTexture(gl.TEXTURE0);
 }
 release(){if(this.current){this.gl.deleteTexture(this.current.texture);this.gl.deleteFramebuffer(this.current.framebuffer);}for(const target of this.history??[]){this.gl.deleteTexture(target.texture);this.gl.deleteFramebuffer(target.framebuffer);}this.current=null;this.history=null;this.width=0;this.height=0;this.photo.reset();}
 destroy(){this.release();this.gl.deleteProgram(this.program);}
}
